# Generated by Django 5.1.4 on 2024-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_seat_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
