# Generated by Django 5.1.3 on 2024-12-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InforUser',
        ),
    ]
