# Generated by Django 5.1.3 on 2024-12-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('flights', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='abc',
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.flights'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='type_of_seats',
            field=models.CharField(choices=[(0, 'first class'), (1, 'business'), (2, 'economy')], max_length=200, null=True),
        ),
    ]
