# Generated by Django 5.1.3 on 2024-12-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_flight_id_remove_booking_is_booked_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
