# Generated by Django 5.0.10 on 2024-12-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_flights_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='business_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='economy_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='first_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
    ]
