# Generated by Django 5.1.3 on 2024-12-13 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='flights.flight'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(related_name='flight_of_bookings', to='flights.passenger'),
        ),
    ]
