# Generated by Django 5.1.3 on 2024-12-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_passenger_flight_alter_booking_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passengers',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='flights.flight'),
        ),
    ]
