# Generated by Django 5.1.3 on 2024-12-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_remove_booking_flight_remove_booking_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flight',
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(related_name='flight_of_bookings', to='flights.passenger'),
        ),
    ]
