# Generated by Django 5.1.3 on 2024-12-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_rename_flight_book_booking_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
