# Generated by Django 5.1.3 on 2024-12-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
