# Generated by Django 5.1.4 on 2024-12-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_id_alter_place_id_alter_week_id'),
        ('flights', '0013_ticket'),
    ]

    operations = [
    ]
