# Generated by Django 5.1.4 on 2024-12-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_merge_20241226_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
